# -*- coding: utf-8 -*-


MARITAL_STATUS_GROUPS = { 'MARRIED'           : 'MARRIED',
                          'LIFE PARTNER'      : 'MARRIED',
                          'SINGLE'            : 'SINGLE',
                          'DIVORCED'          : 'DIVORCED/SEPARATED',
                          'SEPARATED'         : 'DIVORCED/SEPARATED',
                           None               : 'UNKNOWN',
                          'UNKNOWN (DEFAULT)' : 'UNKNOWN',
                          'WIDOWED'           : 'WIDOWED'
                        }

RELIGION_GROUPS = { 'CATHOLIC'                : 'CHRISTIAN',
                        'PROTESTANT QUAKER'       : 'CHRISTIAN',
                        'EPISCOPALIAN'            : 'CHRISTIAN',
                        'CHRISTIAN SCIENTIST'     : 'CHRISTIAN',
                        '''JEHOVAH'S WITNESS'''   : 'CHRISTIAN',
                        'UNITARIAN-UNIVERSALIST'  : 'CHRISTIAN',
                        '7TH DAY ADVENTIST'       : 'CHRISTIAN',
                        'BAPTIST'                 : 'CHRISTIAN',
                        'LUTHERAN'                : 'CHRISTIAN',
                        'METHODIST'               : 'CHRISTIAN',
                        'GREEK ORTHODOX'          : 'ORTHODOX',
                        'ROMANIAN EAST. ORTH'     : 'ORTHODOX',
                        'JEWISH'                  : 'JEWISH/HEBREW',
                        'HEBREW'                  : 'JEWISH/HEBREW',
                        'NOT SPECIFIED'           : 'NONE',
                        'UNOBTAINABLE'            : 'NONE',
                        'OTHER'                   : 'NONE',
                         None                     : 'NONE',
                        'BUDDHIST'                : 'BUDDHIST/HINDU',
                        'HINDU'                   : 'BUDDHIST/HINDU',
                        'MUSLIM'                  : 'MUSLIM'
                                  
                    }

ETHNIC_GROUPS = {'WHITE'  													              :  'WHITE',
                     'WHITE - RUSSIAN'  											           :  'WHITE',
                     'WHITE - OTHER EUROPEAN'  									           :  'WHITE',
                     'PORTUGUESE'  												              :  'WHITE',
                     'WHITE - BRAZILIAN'  									              :  'WHITE',
                     'WHITE - EASTERN EUROPEAN'  								           :  'WHITE',
                     'BLACK/AFRICAN AMERICAN'  									           :  'BLACK',
                     'BLACK/CAPE VERDEAN'  										           :  'BLACK',
                     'BLACK/HAITIAN'  											              :  'BLACK',
                     'BLACK/AFRICAN'  											              :  'BLACK',
                     'UNKNOWN/NOT SPECIFIED'  								              :  'NONE',
                     'UNABLE TO OBTAIN' 									                 :  'NONE',
                     'PATIENT DECLINED TO ANSWER'  								        :  'NONE',
                     'HISPANIC OR LATINO'  										           :  'HISPANIC',
                     'HISPANIC/LATINO - PUERTO RICAN'  							        :  'HISPANIC',
                     'HISPANIC/LATINO - DOMINICAN'  								        :  'HISPANIC',
                     'HISPANIC/LATINO - GUATEMALAN'  							           :  'HISPANIC',
                     'HISPANIC/LATINO - CUBAN'  								           :  'HISPANIC',
                     'HISPANIC/LATINO - SALVADORAN'  							           :  'HISPANIC',
                     'HISPANIC/LATINO - MEXICAN'  								           :  'HISPANIC',
                     'HISPANIC/LATINO - CENTRAL AMERICAN (OTHER)'  				     :  'HISPANIC',
                     'HISPANIC/LATINO - COLOMBIAN'  								        :  'HISPANIC',
                     'SOUTH AMERICAN'  											           :  'HISPANIC',
                     'HISPANIC/LATINO - HONDURAN'  								        :  'HISPANIC',
                     'OTHER' 													                 :  'OTHER',
                     'MULTI RACE ETHNICITY'  									           :  'OTHER',
                     'AMERICAN INDIAN/ALASKA NATIVE'  							        :  'OTHER',
                     'MIDDLE EASTERN'  											           :  'OTHER',
                     'NATIVE HAWAIIAN OR OTHER PACIFIC ISLANDER'  				     :  'OTHER',
                     'CARIBBEAN ISLAND'  										              :  'OTHER',
                     'AMERICAN INDIAN/ALASKA NATIVE FEDERALLY RECOGNIZED TRIBE'    :  'OTHER',
                     'ASIAN'  													              :  'ASIAN',
                     'ASIAN - CHINESE'  											           :  'ASIAN',
                     'ASIAN - ASIAN INDIAN'  									           :  'ASIAN',
                     'ASIAN - VIETNAMESE'  										           :  'ASIAN',
                     'ASIAN - FILIPINO'  										              :  'ASIAN',
                     'ASIAN - CAMBODIAN'  										           :  'ASIAN',
                     'ASIAN - OTHER'  											              :  'ASIAN',
                     'ASIAN - KOREAN'  											           :  'ASIAN',
                     'ASIAN - JAPANESE'  										              :  'ASIAN',
                     'ASIAN - THAI'  											              :  'ASIAN'    
                    }

LAB_TEST = [{'test' : 'BLOOD_UREA_NITROGEN'  , 'itemid' : '51006'},
            {'test' : 'PLATELET_COUNT'       , 'itemid' : '51265' },
            {'test' : 'HEMATROCRIT'          , 'itemid' : '51221'},
            {'test' : 'POTASSSIUM'           , 'itemid' : '50971'},
            {'test' : 'SODIUM'               , 'itemid' : '50983'},
            {'test' : 'CREATININE'           , 'itemid' : '50912'},
            {'test' : 'BICARBONATE'          , 'itemid' : '50882'},
            {'test' : 'WHITE_BLOOD_CELLS'    , 'itemid' : '51301'},
            {'test' : 'BLOOD_GLUCOSE'        , 'itemid' : '50809,50931'},
            {'test' : 'ALBUMIN'              , 'itemid':'50862'}]

PHYSIO_MEASURES = [{'name': 'HR', 'itemid': '220045, 211'},
                   {'name':'RESP_RATE', 'itemid': '8113, 3603, 220210, 618'},
                   {'name':'SYS_PRESS', 'itemid': '51,442,455,6701,220179,220050'},
                   {'name':'DIAS_PRESS','itemid': '8368,8440,8441,8555,220180,220051'},
                   ##{'name':'URINE_OUTPUT', 'itemid': '40055, 226559'}, INCORRECT ITEMIDS
                   {'name':'TEMP', 'itemid': '223761,678'},
                   ##{'name':'CVP', 'itemid': '113, 220074'},
                   ##{'name':'ART_PH', 'itemid': '4753, 1126'},
                   {'name':'SPO2', 'itemid':'646, 220277'}]
    